### ISSUE TITLE
aws_cloudformation_stack.datapipeline resource does not produce an array

### ISSUE THREAD

**Issue by abferm** [cloudposse/terraform-aws-efs-backup#14]
The "datapipeline_ids" output references the "aws_cloudformation_stack.datapipeline" as though it produces the array. This hasn't been the case since 8bc76efd352af57d1f43605948f6f7e38e307130.

```
Error: Error refreshing state: 1 error(s) occurred:

* module.efs_backup.output.datapipeline_ids: __builtin_StringToInt: strconv.ParseInt: parsing "DataPipelineId": invalid syntax in:

${aws_cloudformation_stack.datapipeline.*.outputs["DataPipelineId"]}

```

**Comment by osterman** [comment]
Fixed by https://github.com/cloudposse/terraform-aws-efs-backup/pull/15
