### ISSUE TITLE
 "current": [REMOVED] Defaults to current provider region if no other filtering is enabled

### ISSUE THREAD

**Issue by cjgratacos** [cloudposse/terraform-aws-efs-backup#39]
The module is failing and I am getting the following error:  
`Error: module.jenkins_efs_backup.data.aws_region.default: "current": [REMOVED] Defaults to current provider region if no other filtering is enabled`

The cause of the issue is in here: https://github.com/cloudposse/terraform-aws-efs-backup/blob/82fe791ff029d6b7f42b3a9d06364d55cd4c1ec3/main.tf#L1-L4
The solution is to remove the `current = true` since it is deprecated and throwing an error for Terraform v0.11.13.

Reference: https://www.terraform.io/docs/providers/aws/d/region.html

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/terraform-aws-efs-backup/releases/tag/0.9.0
